version: '3'

services:
  spiders:
    container_name: spiders
    build: ./spiders
    command: python main.py
    volumes:
      - ./spiders:/app

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpwd
    ports:
      - 27017:27017
